- name: Install kubectl v1.21.1
  run: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    curl -LO https://dl.k8s.io/release/v1.21.1/bin/linux/amd64/kubectl

# - name: Install kubectl
#   yum:
#     name: kubectl
#     state: present
#   become: yes
